### ISSUE TITLE
Something is error everytime launching terminal

### ISSUE THREAD

**Issue by serpentarius-hollow** [andresgongora/synth-shell#166]
Hello, I love your script here. I'm linux noob and currently using default xfce terminal. After installing your script as current-user only why does everytime I launch terminal it seems to doing some network query and it gives me error. The full error message is:

>Error: error sending query: Could not send or receive, because of network error

The rest is fine, it's just kinda annoying everytime I launch terminal. I would like to disable the sending network query thing if I can. How do I achieve that? 

Thank you.

**Comment by serpentarius-hollow** [comment]
I just re-installed and leave status uninstalled.

**Comment by andresgongora** [comment]
Hi @serpentarius-hollow . I',m glad you like my scripts.

This error is caused by `status.sh`, and almost certainly by the part of the script that tries to tell you your external IP. Because the PC has no way to tell by itself what IP it has on the public internet, it is sending a request to Google (if I'm not mistaken) through one of several tools (I recommend you install `ldns`, its quite fast, or `bind-tools` if the former is not available).

However, if you don't want your external IP, you can disable the query completely. This has the added effect of making the script much faster, as it no longer has to wait for an external IP. And also solves issues if your PCs has no internet connection (the query times out after 1 second, but you would have to wait that long). To disable only the query, edit `~/.config/synth-shell/status.config` and remove `EXTERNALIPV4` from `print_info` (its on line 85).

Please let me know if it worked :)
